### ISSUE TITLE
Tex representation of a figure

### ISSUE THREAD

**Issue by vsoch** [penrose/arxiv-miner#1]
Is the following tex the only way that a figure can be represented?

```python
thing = "\\begin{tikzpicture}"
```
I have used the same (with figure) in some papers, and I saw this commented out:

```python
#thing = "\\begin{figure}"
```

@dormaayan are you only interested in the first tag? There are definitely figure tags in there. If it's the case that the figures (graphics) aren't included this would not represent the true number of figures in the paper, no?

**Comment by dormaayan** [comment]
@vsoch Oh, this is commented out since in some stage I was interested just on TikZ things.
It definitely should be the second one...

**Comment by dormaayan** [comment]
@vsoch The problem is that in most cases they are nested:
`\begin{figure} ... 
\begin{tikzpicture } ` and we don't want to count them twice.

I think that at this stage `\begin{figure}` is a good enough heuristic

**Comment by vsoch** [comment]
ah good point! Yes I'm seeing that [here too](https://tex.stackexchange.com/questions/255686/which-is-better-practice-rendering-figures-on-the-fly-or-importing-them-as-ima). I agree let's stick to figure - it seems to be the global identifier (that other packages wrap). Closing issue.
