### ISSUE TITLE
Filtering down to subset of papers

### ISSUE THREAD

**Issue by vsoch** [penrose/arxiv-miner#2]
heyo @dormaayan ! I noticed that we have a function to return a boolean if it's a math paper, based on finding the tag:

```python
#Given a paper name, return whether it is a math paper or not
def isMathPaper(paperName):
    return subjects[paperName].count("math.") > 0
```

Is there any reason to limit our set at this point? The categories are pretty fuzzy overall, maybe just look at all of them?

**Comment by dormaayan** [comment]
@vsoch Yes, now when we have resources we can check all the subjects, not just math. It is also interesting to get the statistics over sub categories as well...

**Comment by vsoch** [comment]
Gotcha! Will do.
